services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${DATABASE_URL}
      - GAMMA_CLIENT_ID=${DATABASE_URL}
      - GAMMA_REDIRECT_URI=${DATABASE_URL}
      - GAMMA_CLIENT_SECRET=${DATABASE_URL}
      - frontend_url=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: screenit2
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d screenit2"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: